version: '3.9'

services:
  dash:
    container_name: ${PROJECT_NAME:-base_repository}_dash
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE:-dev}
      args:
        - PORT=${DASH_PORT:-3004}
    ports:
      - "${DASH_PORT:-3004}:${DASH_PORT:-3004}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=external_network
      - traefik.http.routers.dash.entrypoints=${ENTRYPOINT:-http}
      - traefik.http.routers.dash.tls=${TLS:-false}
      - traefik.http.routers.dash.tls.certresolver=lets-encrypt
      - traefik.http.routers.dash.rule=Host(`${DASH_DOMAIN:-dash.localhost}`)
      - traefik.http.services.dash.loadbalancer.server.port=${DASH_PORT:-3004}
    environment:
      - PORT=${DASH_PORT:-3004}
    volumes:
      - dash:/app
    networks:
      - external_network

networks:
  external_network:
    external: true
    name:  external_${PROJECT_NAME:-base_repository}_network

volumes:
  dash:
    driver: "local"
    name: ${PROJECT_NAME:-base_repository}_dash
